apiVersion: apps/v1
kind: Deployment
metadata:
  name: gfrdes
spec:
  replicas: 1
  selector:
    matchLabels:
      app:gfrdes
  template:
    metadata:
      labels:
        app:gfrdes
    spec:
      containers:
      - image: okteto.dev/gfrdes:latest
        name: gfrdes
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "c8a13923-789c-45f8-a3f1-ecb7b2a31521"
        - name: Vless_Path
          value: "/c8a13923-789c-45f8-a3f1-ecb7b2a31521"
        - name: Vmess_UUID
          value: "7dc83690-c01e-4531-a775-08b3699d64a5"
        - name: Vmess_Path
          value: "/7dc83690-c01e-4531-a775-08b3699d64a5"
        - name: Share_Path
          value: "/v2link"
