apiVersion: v1
kind: Service
metadata:
  name:gfrdes
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "gfrdes"
    port: 8080
  selector:
    app:gfrdes
